-- Attandant 프로젝트 데이터베이스 스키마

-- attendance_records 테이블
CREATE TABLE IF NOT EXISTS public.attendance_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  record_type TEXT NOT NULL,
  timestamp TIMESTAMPTZ DEFAULT now(),
  location TEXT,
  notes TEXT,
  reason TEXT,
  night_off_time TIMESTAMPTZ,
  extra_minutes INTEGER
);

-- attendance_settings 테이블
CREATE TABLE IF NOT EXISTS public.attendance_settings (
  id INTEGER PRIMARY KEY,
  day_of_week INTEGER NOT NULL,
  is_working_day BOOLEAN NOT NULL,
  work_start_time VARCHAR NOT NULL,
  work_end_time VARCHAR NOT NULL,
  lunch_start_time VARCHAR,
  lunch_end_time VARCHAR,
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- holiday_works 테이블
CREATE TABLE IF NOT EXISTS public.holiday_works (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  date DATE NOT NULL,
  work_minutes INTEGER NOT NULL,
  description TEXT,
  created_by UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ DEFAULT now(),
  extra_overtime_minutes INTEGER
);

-- leave_requests 테이블
CREATE TABLE IF NOT EXISTS public.leave_requests (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  leave_type VARCHAR NOT NULL,
  leave_source VARCHAR,
  special_leave_id UUID,
  total_days NUMERIC NOT NULL,
  reason TEXT,
  status VARCHAR NOT NULL,
  approval_date TIMESTAMP,
  approved_by UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- monthly_work_stats 테이블
CREATE TABLE IF NOT EXISTS public.monthly_work_stats (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  year INTEGER NOT NULL,
  month INTEGER NOT NULL,
  name TEXT,
  total_work_minutes INTEGER NOT NULL,
  overtime_minutes INTEGER NOT NULL,
  holiday_work_minutes INTEGER NOT NULL,
  holiday_exceeded_minutes INTEGER,
  late_minutes INTEGER,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- profiles_new 테이블
CREATE TABLE IF NOT EXISTS public.profiles_new (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT,
  department TEXT,
  role TEXT DEFAULT 'staff',
  photo_url TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ
);

-- Row Level Security 설정
ALTER TABLE public.attendance_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.holiday_works ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leave_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.monthly_work_stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles_new ENABLE ROW LEVEL SECURITY;

-- 기본 정책 설정
-- 관리자는 모든 데이터 접근 가능
-- 일반 사용자는 자신의 데이터만 접근 가능 